version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      - image: 'circleci/python:2.7'

    working_directory: ~/bp-poke-pacman-frontend

    steps:
      - checkout
      - aws-s3/sync:
          from: ~/bp-poke-pacman-frontend
          to: 's3://myburger-pacman'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true